name: tests
on:
  pull_request:
    paths-ignore: ['dist/**', '*.md']
  push:
    branches: [0.9.x, main, next]
    paths-ignore: ['dist/**', '*.md']
jobs:
  test:
    name: PHP ${{ matrix.php }}, Laravel ${{ matrix.laravel }}, ${{ matrix.dependencies }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['7.3', '7.4']
        laravel: [5.5.*, 5.6.*, 5.7.*, 5.8.*, 6.*, 7.*, 8.*]
        dependencies: [prefer-lowest, prefer-stable]
        # exclude:
        #   - laravel: 5.5.*
        #     php: '7.3'
        #     dependencies: prefer-lowest
        #   - laravel: 5.6.*
        #     php: '7.3'
        #     dependencies: prefer-lowest
        include:
          - testbench: '*'
          - php: '8.0'
            laravel: 6.*
          - php: '8.0'
            laravel: 7.*
          - php: '8.0'
            laravel: 8.*
          - php: '8.0'
            laravel: dev-master
            testbench: dev-master
          - php: '8.1'
            laravel: 8.*
          - php: '8.1'
            laravel: dev-master
            testbench: dev-master
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
      - uses: actions/cache@v2
        with:
          path: ~/.composer/cache/files
          key: php-${{ matrix.php }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: php-${{ matrix.php }}-composer-
      - run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-update --no-interaction
          composer update --${{ matrix.dependencies }} --prefer-dist --no-interaction --no-suggest
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: npm-
      - run: |
          npm install
          npm run build
      - run: vendor/bin/phpunit --testdox --colors=always
      - run: npm test
